name: Daily Report

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  build-and-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm install
      - run: npm run build

      - run: npm run start
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
          TELEGRAM_API_KEY: ${{ '8867519706:AAGMCgZzGyJJwBmDC-mIlIeLe8iS5aswtSo' }}
          TELEGRAM_CHAT_ID: ${{ '475235122' }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
